packages/amplify-auth-sdk/src/environments.js
packages/amplify-cli-auth/src/commands/server-info.js
packages/amplify-cli-utils/src/environments.js

https://techweb.axway.com/jira/browse/CLI-36

fix(auth): Updated environment auth settings for new realm. Fixes CLI-36.

---

packages/amplify-cli-pm/src/commands/view.js

Fixes CLI-61.
https://techweb.axway.com/jira/browse/CLI-61

fix(pm): Added filtering to view package output.

---

package.json
packages/amplify-auth-sdk/package.json
packages/amplify-auth-sdk/src/errors.js
packages/amplify-auth-sdk/src/index.js
packages/amplify-auth-sdk/src/stores/secure-store.js
packages/amplify-auth-sdk/test/test-auth.js
packages/amplify-auth-sdk/test/test-token-store.js
packages/amplify-cli-auth/package.json
packages/amplify-cli-auth/src/commands/login.js
packages/amplify-cli-auth/src/commands/logout.js
packages/amplify-cli-pm/package.json
packages/amplify-cli-utils/src/auth.js
packages/amplify-cli/README.md
packages/amplify-cli/package.json
yarn.lock

https://techweb.axway.com/jira/browse/CLI-63

[CLI-63] Moved keytar from a direct npm dependency to an indirect dependency that is installed at runtime.

---

packages/amplify-request/package.json
yarn.lock

chore: Bumped amplify-config dep.

---

packages/amplify-auth-sdk/package.json
yarn.lock

https://techweb.axway.com/jira/browse/CLI-73
Also ran `yarn upgrade` so the `yarn.lock` is up to date

chore(deps): update packages

---

packages/amplify-cli-pm/package.json
yarn.lock

ora 4 has a bug that seems to prevent the process from exiting on Windows in certain cases (https://github.com/sindresorhus/ora/issues/136), downgrade to fix this for now
Fixes CLI-76

fix(pm): downgrade ora

---

packages/amplify-cli-pm/package.json
yarn.lock

https://techweb.axway.com/jira/browse/CLI-76

chore: @axway/amplify-cli-pm@1.4.1

---

packages/amplify-auth-sdk/package.json
packages/amplify-auth-sdk/src/stores/file-store.js
packages/amplify-auth-sdk/src/stores/secure-store.js
yarn.lock

fix: Fixed bug where bad decrypts implied key was also bad.
chore: Updated to keytar@5.0.0.
JIRA: https://techweb.axway.com/jira/browse/CLI-80

No longer nuke key if decrypt fails

---

packages/amplify-auth-sdk/package.json
packages/amplify-auth-sdk/src/index.js
packages/amplify-cli-auth/package.json
packages/amplify-cli-auth/src/commands/switch.js
packages/amplify-cli-pm/package.json
packages/amplify-registry-sdk/package.json
yarn.lock

fix: Fixed expires prop in find().

---

packages/amplify-sdk/package.json
yarn.lock

chore: Updated npm deps.

---

packages/amplify-auth-sdk/package.json
packages/amplify-auth-sdk/src/authenticators/signed-jwt.js

https://jira.axway.com/browse/CLI-92

fix(amplify-auth-sdk): Fixed bug with JWT expiration. Fixes CLI-92.

---

packages/amplify-auth-sdk/package.json
packages/amplify-cli-auth/package.json
packages/amplify-cli-auth/src/commands/login.js
packages/amplify-cli-auth/src/commands/switch.js
packages/amplify-cli-pm/package.json
packages/amplify-cli-utils/package.json
packages/amplify-registry-sdk/package.json
packages/amplify-sdk/package.json
yarn.lock

refactor(amplify-cli-auth): Switched from inquirer to enquirer.

---

packages/amplify-sdk/package.json
yarn.lock

amplify-sdk@1.0.3

---

packages/amplify-auth-sdk/src/authenticators/authenticator.js
packages/amplify-cli-auth/src/commands/logout.js
packages/amplify-cli-pm/src/commands/search.js
packages/amplify-cli-pm/src/commands/uninstall.js
packages/amplify-cli-pm/src/commands/view.js

fix(auth-sdk): Handle undefined response for http request errors.
Hide lesser used aliases.

Bug fix, alias tweaks

---

packages/amplify-auth-sdk/CHANGELOG.md
packages/amplify-auth-sdk/package.json
packages/amplify-cli-auth/CHANGELOG.md
packages/amplify-cli-auth/package.json
packages/amplify-cli-pm/CHANGELOG.md
packages/amplify-cli-pm/package.json
packages/amplify-cli-utils/CHANGELOG.md
packages/amplify-cli-utils/package.json
packages/amplify-cli/CHANGELOG.md
packages/amplify-cli/package.json
packages/amplify-config/CHANGELOG.md
packages/amplify-config/package.json
packages/amplify-registry-sdk/CHANGELOG.md
packages/amplify-registry-sdk/package.json
packages/amplify-request/package.json
packages/amplify-sdk/CHANGELOG.md
packages/amplify-sdk/package.json
packages/amplify-sdk/src/index.js
yarn.lock

fix(amplify-sdk): Fixed fetching org info where account does not have a platform account.
doc: Added changelogs.

v2.0.0-rc2

---

docs/Release Notes/AMPLIFY CLI 2.0.0.md
packages/amplify-auth-sdk/CHANGELOG.md
packages/amplify-auth-sdk/README.md
packages/amplify-auth-sdk/src/stores/file-store.js
packages/amplify-auth-sdk/src/stores/secure-store.js

fix(auth-sdk):  Added token store backwards compatibility by writing both a v2 and v1 versions of the token store.

Token store backwards compat

---

packages/amplify-sdk/CHANGELOG.md
packages/amplify-sdk/src/index.js

feat(amplify-sdk): Improved error messages.
feat(amplify-sdk): Added server error response 'code' to exceptions.
fix(amplify-sdk): Added Titanium app 'name' to list of required build verify parameters.
fix(amplify-sdk): Added missing 'fingerprint_description' and 'org_id' to build verify request parameters.

AMPLIFY SDK improved error messages and added missing build verify params

---

packages/amplify-config/CHANGELOG.md
packages/amplify-config/src/index.js
packages/amplify-sdk/CHANGELOG.md
packages/amplify-sdk/src/index.js

fix(amplify-conifg): Copy extension packages during first time migration from AMPLIFY CLI structure. [CLI-103]
feat(amplify-sdk:ti): Added query string params argument to ti.setApp().

[CLI-103] Fixed AMPLIFY CLI config migration

---

packages/axway-cli/CHANGELOG.md
packages/axway-cli/src/main.js
packages/axway-cli/templates/help.tpl

JIRA: https://jira.axway.com/browse/CLI-110

chore: Added deprecation warning for Node.js 10 and older.

---

packages/amplify-cli-pm/CHANGELOG.md
packages/amplify-cli-pm/src/commands/install.js
packages/amplify-cli-pm/src/commands/purge.js
packages/amplify-cli-pm/src/commands/uninstall.js
packages/amplify-cli-pm/src/commands/update.js
packages/amplify-cli-pm/src/commands/use.js
packages/amplify-cli-pm/src/commands/view.js
packages/amplify-cli-pm/src/utils.js
packages/amplify-registry-sdk/src/registry.js
packages/amplify-sdk/CHANGELOG.md

* feat(install): Show the command to use the newly installed CLI extension. Fixes [CLI-68](https://jira.axway.com/browse/CLI-68).
* fix(update): Show package name and version during install steps. Fixes [CLI-109](https://jira.axway.com/browse/CLI-109).

Package manager CLI improvements:

---

packages/amplify-cli-pm/src/commands/install.js
packages/amplify-sdk/CHANGELOG.md
packages/amplify-sdk/src/authenticators/authenticator.js
packages/amplify-sdk/test/test-owner-password.js
packages/amplify-sdk/test/test-signed-jwt.js

JIRA: https://jira.axway.com/browse/CLI-118

fix(amplify-sdk): Gracefully handle fetch user info request failures.

---

packages/amplify-cli-auth/CHANGELOG.md
packages/amplify-cli-auth/src/commands/login.js
packages/amplify-sdk/src/auth.js
packages/amplify-sdk/src/authenticators/authenticator.js

JIRA: https://jira.axway.com/browse/CLI-79

feat(login): Added feedback when launching the web browser for an interactive login.

---

packages/amplify-cli-auth/src/commands/list.js
packages/amplify-cli-auth/src/commands/login.js
packages/amplify-cli-pm/src/commands/install.js
packages/amplify-sdk/CHANGELOG.md
packages/amplify-sdk/src/auth.js
packages/amplify-sdk/src/authenticators/authenticator.js
packages/amplify-sdk/src/stores/token-store.js

JIRA: https://jira.axway.com/browse/CLI-119

fix(auth): Handle authentication that does not return a refresh token.

---

packages/amplify-cli-auth/CHANGELOG.md
packages/amplify-cli-auth/src/commands/login.js
packages/amplify-cli-auth/src/commands/logout.js
packages/amplify-cli-auth/src/commands/switch.js
packages/amplify-cli-utils/CHANGELOG.md
packages/amplify-cli-utils/src/index.js
packages/amplify-config/package.json
packages/amplify-sdk/CHANGELOG.md
packages/amplify-sdk/src/amplify-sdk.js
packages/amplify-sdk/src/authenticators/authenticator.js
packages/amplify-sdk/src/index.js
packages/axway-cli-oum/src/org/idp.js
packages/axway-cli-oum/src/user/credentials.js
yarn.lock

JIRA: https://jira.axway.com/browse/CLI-116

feat: Improved handling of headless environments

---

packages/amplify-cli-auth/CHANGELOG.md
packages/amplify-cli-pm/CHANGELOG.md
packages/amplify-cli-utils/CHANGELOG.md
packages/amplify-registry-sdk/CHANGELOG.md
packages/amplify-sdk/CHANGELOG.md
packages/amplify-sdk/src/amplify-sdk.js
packages/axway-cli-oum/CHANGELOG.md
packages/axway-cli/CHANGELOG.md

PR: https://jira.axway.com/browse/CLI-121

fix(amplify-sdk): Cast org id with parseInt()

---

packages/axway-cli/CHANGELOG.md
packages/axway-cli/src/main.js
test/axway/help/32-bit-deprecation.mustache
test/axway/help/unsupported-arch.mustache
test/axway/test-axway.js
test/helpers/arch-shim-arm.js
test/helpers/arch-shim-ia32.js
test/helpers/index.js

chore: Added unsupported architecture and 32-bit architecture deprecation warning to banner. Fixes [CLI-130](https://jira.axway.com/browse/CLI-130).

Architecture warnings

---

packages/axway-cli/CHANGELOG.md
packages/axway-cli/scripts/postinstall.js

https://jira.axway.com/browse/CLI-128

doc: Added "install Axway Central CLI" to post install next steps verbiage.

---

packages/amplify-cli-auth/CHANGELOG.md
packages/amplify-cli-auth/README.md
packages/amplify-cli-auth/src/commands/login.js
packages/amplify-sdk/CHANGELOG.md
packages/amplify-sdk/README.md
packages/amplify-sdk/package.json
packages/amplify-sdk/src/amplify-sdk.js
packages/amplify-sdk/src/auth.js
packages/amplify-sdk/src/stores/file-store.js
packages/amplify-sdk/src/stores/token-store.js
packages/amplify-sdk/test/common.js
packages/amplify-sdk/test/test-sdk.js
test/auth/list/service-bar-platform-account.mustache
test/auth/login/bad-credentials.mustache
test/auth/login/help.mustache
test/auth/login/missing-client-secret.mustache
test/auth/test-auth.js
test/helpers/index.js
test/helpers/platform-routes.js
yarn.lock

Implementation ticket: https://jira.axway.com/browse/APIGOV-19229
Testing ticket: https://jira.axway.com/browse/APIGOV-19230

Add platform tooling username/password auth to service logins

---

packages/amplify-cli-auth/src/commands/switch.js
packages/amplify-sdk/test/test-sdk.js

JIRA: https://jira.axway.com/browse/APIGOV-19417

fix(auth:switch): Fix non-interactive flow for switching default account and org.

---

packages/axway-cli-pm/src/commands/install.js
packages/axway-cli-pm/src/commands/purge.js
packages/axway-cli-pm/src/commands/uninstall.js
packages/axway-cli-pm/src/commands/update.js
packages/axway-cli/README.md
packages/axway-cli/src/commands/config.js
packages/axway-cli/src/main.js
yarn.lock

feat: Added 'update.check' option to disable update checks.
fix: Only show package updates once every 30 minutes.

Improve update check notifications

---

packages/amplify-sdk/CHANGELOG.md
packages/amplify-sdk/src/amplify-sdk.js
test/helpers/platform-routes.js
test/org/usage/bundle-saas.mustache

feat(amplify-sdk): Added new function to get entitlement info which is used by the org usage report to populate bundle metric names.
JIRA: https://jira.axway.com/browse/APIGOV-19513

feat(amplify-sdk): Added new function to get entitlement info

---

packages/amplify-sdk/CHANGELOG.md
packages/amplify-sdk/src/amplify-sdk.js
packages/amplify-sdk/test/test-sdk.js
packages/axway-cli-oum/.eslintrc
packages/axway-cli-oum/CHANGELOG.md
packages/axway-cli-oum/src/org/activity.js
packages/axway-cli-oum/src/org/usage.js
packages/axway-cli-oum/src/user/activity.js
test/org/activity/help.mustache
test/org/usage/help.mustache
test/user/activity/help.mustache
yarn.lock

JIRA: https://jira.axway.com/browse/APIGOV-19922

APIGOV-19922: Usage month range support

---

gulpfile.js
packages/amplify-sdk/CHANGELOG.md
packages/amplify-sdk/src/amplify-sdk.js
packages/amplify-sdk/src/auth.js
packages/amplify-sdk/src/errors.js
packages/axway-cli-auth/CHANGELOG.md
packages/axway-cli-auth/src/auth/list.js
packages/axway-cli-auth/src/auth/login.js
packages/axway-cli-auth/src/auth/switch.js
packages/axway-cli-auth/src/auth/whoami.js
packages/axway-cli-oum/src/org/user/roles.js
test/auth/test-auth.js
test/helpers/auth-routes.js
test/helpers/platform-routes.js

JIRA: https://jira.axway.com/browse/APIGOV-20857

fix: Validate that accounts have not been invalidated when listing authenticated accounts

---

packages/amplify-cli-utils/test/test-auth.js
packages/amplify-sdk/CHANGELOG.md
packages/amplify-sdk/src/amplify-sdk.js
packages/axway-cli-auth/CHANGELOG.md
packages/axway-cli-auth/src/auth/list.js
packages/axway-cli-auth/src/auth/login.js
packages/axway-cli-auth/src/auth/switch.js
packages/axway-cli-auth/src/auth/whoami.js
packages/axway-cli-auth/src/lib/info.js
test/auth/list/foo-bar-platform-account.mustache
test/auth/list/platform-service-accounts.mustache
test/auth/list/service-bar-account.mustache
test/auth/list/service-bar-platform-account.mustache
test/auth/login/already-authenticated.mustache
test/auth/login/success-headless.mustache
test/auth/login/success-service-not-default.mustache
test/auth/login/success-service.mustache
test/auth/login/success.mustache
test/auth/test-auth.js
test/auth/whoami/foo-bar-account.mustache
test/helpers/platform-routes.js
yarn.lock

Added ability to switch your selected team when running `axway auth switch`.
For platform accounts, it will launch your browser to select the org, then return to the command line to allow you to select a team:
```
$ axway auth switch
AXWAY CLI, version 3.0.2
Copyright (c) 2018-2021, Axway, Inc. All Rights Reserved.
Launching web browser to switch organization...
? Select an team to use …
❯ Default Team (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
devteam (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
```
Once you select a team, it will output your org and team info:
```
$ axway auth switch
AXWAY CLI, version 3.0.2
Copyright (c) 2018-2021, Axway, Inc. All Rights Reserved.
Launching web browser to switch organization...
✔ Select an team to use · devteam
Default account set to cbarber@axway.com in …
```

APIGOV-20941: Ability to select team

---

packages/axway-cli-pm/package.json
packages/axway-cli-pm/src/commands/install.js
packages/axway-cli-pm/src/commands/purge.js
packages/axway-cli-pm/src/commands/update.js
packages/axway-cli-pm/src/utils.js
yarn.lock

JIRA:
https://jira.axway.com/browse/APIGOV-21697

APIGOV-21697: Replace dependency "listr" with "listr2"

---

packages/amplify-sdk/CHANGELOG.md
packages/amplify-sdk/src/amplify-sdk.js

JIRA: https://jira.axway.com/browse/APIGOV-22156

fix(auth): During logout, redirect to correct logout page with signin button
